### ISSUE TITLE
Pre-submission checklist

### ISSUE THREAD

**Issue by bpbond** [bpbond/rh-changes#22]
- [x] Contact Christian and Markus re data use and name
- [x] Make sure supplementary info cites all FLUXNET datasets used
- [x] Contact FLUXNET data providers and update? Check requirements
- [x] Re-contact Yiqi and update
- [x] Change "BGI" to "MTE" and cite Jung (2011) not Beer (2010)
- [x] Have Min re-run with final numbers
- [x] Re-run all scripts
- [x] Check all numbers and text
- [x] Double-space and line numbers
